version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    environment:
      - POSTGRES_USER=saltdb@canine-cloud
      - POSTGRES_PASSWORD=saltsecret1!
      - POSTGRES_DB=saltdb
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always