#spring.application.name=sideeffects
spring:
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never
      platform: postgresql
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${AZURE_DB_USER}
    password: ${AZURE_DB_PWD}
    url: ${AZURE_DB_CONNECTION_STRING}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true