#spring.application.name=sideeffects
spring:
  output:
    ansi:
      enabled: always
  sql:
    init:
      platform: mssql-jdbc
      mode: always
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${AZURE_DB_USER}
#    username: saltdb@canine-cloud
    password: ${AZURE_DB_PWD}
#    password: saltsecret1!
    url: ${AZURE_DB_CONNECTION_STRING}
#    url: jdbc:sqlserver://canine-cloud.database.windows.net:1433;database=salt
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

#  cloud:
#    azure:
#      storage:
#        blob:
#          connection-string: ${AZURE_BLOB_CONNECTION_STRING}