INSERT INTO side_effects (name) VALUES ('Nausea');
INSERT INTO side_effects (name) VALUES ('Headache');
INSERT INTO products (name,brand,description) VALUES ('Alvedon 500mg', 'Alvedon', 'Paracetamol');
INSERT INTO products (name,brand,description) VALUES ('Ibuprofen 400mg', 'Ipren', 'Ibuprofen');
INSERT INTO products_side_effect_list (product_id, side_effect_list_id) VALUES ('1','1');
INSERT INTO products_side_effect_list (product_id, side_effect_list_id) VALUES ('2','1');
INSERT INTO products_side_effect_list (product_id, side_effect_list_id) VALUES ('2','2');
INSERT INTO reports (product_id, side_effect_id, age) VALUES ('2', '1', '34');
INSERT INTO reports (product_id, side_effect_id, age) VALUES ('2', '2', '34');
INSERT INTO reports (product_id, side_effect_id, age) VALUES ('2', '2', '21');
INSERT INTO reports (product_id, side_effect_id, age) VALUES ('2', '1', '34');
INSERT INTO reports (product_id, side_effect_id, age) VALUES ('1', '1', '26');