--INSERT INTO products (name,brand,description) VALUES ('Alvedon 500mg', 'Alvedon', 'Paracetamol');
--INSERT INTO products (name,brand,description) VALUES ('Ibuprofen 400mg', 'Ipren', 'Ibuprofen');
--INSERT INTO side_effects (name) VALUES ('Nausea');
--INSERT INTO side_effects (name) VALUES ('Headache');
--INSERT INTO reports (product_id, side_effect_id, age) VALUES ('2', '1', '34');
--INSERT INTO reports (product_id, side_effect_id, age) VALUES ('2', '2', '21');
--INSERT INTO reports (product_id, side_effect_id, age) VALUES ('2', '1', '34');
--INSERT INTO reports (product_id, side_effect_id, age) VALUES ('2', '1', '34');